name: 'SkillLens: PR Review Learning & Developer Growth'
description:
  'Transform PR review feedback into personalized learning paths with Hyperskill
  courses. Automate skill gap analysis and developer education.'
author: 'Hyperskill / SkillLens'

branding:
  icon: 'book-open'
  color: 'purple'

inputs:
  oidc-audience:
    description:
      'OIDC audience to request for ID token (matches backend expected "aud")'
    required: false
    default: 'skilllens.dev'
  default-language:
    description: 'Fallback programming language for topics (e.g., Python)'
    required: false
    default: 'Python'
  max-topics:
    description: 'Maximum number of topics to include'
    required: false
    default: '5'
  min-confidence:
    description: 'Minimum confidence threshold (0..1) for topics'
    required: false
    default: '0.65'
  comment-marker:
    description: 'Hidden marker used to upsert a single PR comment'
    required: false
    default: '<!-- SkillLens:v0 -->'
  fail-on-proxy-error:
    description: 'Fail the workflow if the proxy returns an error (true/false)'
    required: false
    default: 'false'

outputs:
  topics-json:
    description: 'JSON string of returned topics (for debugging/CI artifacts)'
  comment-url:
    description: 'URL of the created/updated PR comment'

runs:
  using: node24
  main: dist/index.js
